version: 2

models:
  - name: fct_user_sessions
    description: Information on user sessions
    columns:
      - name: session_id
        tests:
          - not_null
          - unique
  - name: fct_page_views
    description: Information on page views
    columns:
      - name: page_url
        tests:
          - not_null
          - unique
